include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    unused_import: error
    unused_local_variable: error
    dead_code: error
    todo: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
    - always_put_control_body_on_new_line
    - always_specify_types
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_unnecessary_containers
    - cast_nullable_to_non_nullable
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - join_return_with_assignment
    - library_prefixes
    - literal_only_boolean_expressions
    - no_default_cases
    - no_logic_in_create_state
    - null_check_on_nullable_type_parameter
    - missing_whitespace_between_adjacent_strings
    - sort_pub_dependencies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_void_to_null
    - provide_deprecation_message
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - tighten_type_of_initializing_formals
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - use_super_parameters

dart_code_metrics:
  anti-patterns:
    - long-method:
        exclude:
          - '**/*_cubit.dart'
          - '**/*_bloc.dart'
    - long-parameter-list:
        exclude:
          - '**/*_repo.dart'
          - '**/*_state.dart'
          - '**/*_cubit.dart'
          - '**/*_bloc.dart'
  metrics:
    maximum-nesting-level: 8
    number-of-parameters: 8
    source-lines-of-code: 300
  metrics-exclude:
    - test/**
  rules:
    - always-remove-listener
    - avoid-duplicate-exports
    - avoid-expanded-as-spacer
    - avoid-redundant-async
    - avoid-unrelated-type-assertions
    - avoid-returning-widgets
    - no-equal-then-else
    - prefer-conditional-expressions
    - prefer-correct-test-file-name

    - prefer-single-widget-per-file:
        ignore-private-widgets: true
