targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - lines_longer_than_80_chars
            - prefer_expression_function_bodies
            - always_specify_types
            - non_constant_identifier_names
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
          include_if_null: false
          generic_argument_factories: true
