name: betticos
description: Social betting app. All rights reserved to WealthSecrets (www.wealthsecrets.io)

publish_to: 'none'

version: 1.3.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.1.0+1
  another_flushbar: ^1.10.29
  auto_size_text: ^3.0.0
  barcode: ^2.2.3
  carousel_slider: ^4.0.0
  circular_reveal_animation: ^2.0.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  detectable_text_field: ^2.0.3
  dio: ^5.1.2
  easy_stepper: ^0.5.2+1
  efficient_autocomplete_formfield: ^0.3.2+1
  envied: ^0.3.0
  faker: ^2.0.0
  file_picker: ^5.2.2
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_paystack_plus: ^0.0.1+1
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.5
  flutter_web3: ^2.1.9
  footer: ^0.0.4
  freezed_annotation: ^2.2.0
  get: ^4.6.1
  google_sign_in: ^6.1.0
  http: ^0.13.4
  http_parser: ^4.0.2
  image: ^4.0.17
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.0+2
  ionicons: ^0.2.2
  json_annotation: ^4.8.0
  like_button: ^2.0.4
  line_chart: ^1.1.11
  logging: ^1.0.2
  lottie: ^2.3.2
  modal_bottom_sheet: ^3.0.0-pre
  pin_code_fields: ^7.3.0
  platform: ^3.1.0
  rxdart: ^0.27.5
  settings_ui: ^2.0.2
  share_plus: ^7.0.0
  shared_preferences: ^2.0.11
  slider_captcha: ^1.0.0
  step_progress_indicator: ^1.0.1
  timeago: ^3.1.0
  tutorial_coach_mark: ^1.2.2
  url_launcher: ^6.1.11
  uuid: ^3.0.5
  validators: ^3.0.0
  webviewx: ^0.2.2

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  source_gen: ^1.2.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/json/
    - assets/keys/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 100
