name: betticos
description: Social betting app. All rights reserved to WealthSecrets (www.wealthsecrets.io)

publish_to: "none"

version: 1.3.0+4

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  # algorand_dart: ^1.0.3 #not web
  animated_bottom_navigation_bar: ^0.3.2 #web
  # another_flushbar: ^1.10.28 #web
  another_flushbar: ^1.10.29
  auto_size_text: ^3.0.0 #web
  # bitmap: ^0.1.2 # not web
  # cached_network_image: ^3.2.0 #not web
  carousel_slider: ^4.0.0 #web
  circular_reveal_animation: ^2.0.0 #web
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0 #web
  detectable_text_field: ^2.0.3 #web
  dio: ^4.0.4 #web
  faker: ^2.0.0 #web
  flutter:
    sdk: flutter
  # flutter_local_notifications: ^9.4.0 # not web
  flutter_screenutil: ^5.0.0+2 #web
  flutter_spinkit: ^5.1.0 #web
  flutter_svg: ^0.23.0+1 #web
  freezed_annotation: ^1.1.0 #web
  get: ^4.6.1 #web
  google_sign_in: ^5.3.0 #web
  http: ^0.13.4
  image: ^3.1.3 #web
  image_picker: ^0.8.4+4 #web
  # infinite_scroll_pagination: ^3.1.0 #web
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0 #web
  intl_phone_number_input: ^0.7.0+2 #web
  ionicons: ^0.1.2 #web
  like_button: ^2.0.4 #web
  logging: ^1.0.2 #web
  lottie: ^1.3.0 #web
  modal_bottom_sheet: ^2.0.0 #web
  pin_code_fields: ^7.3.0 #web
  qr_flutter: ^4.0.0
  settings_ui: ^2.0.2 #not web
  share_plus: ^4.0.3 #web
  shared_preferences: ^2.0.11 #web
  # socket_io_client: ^1.0.1 #web
  step_progress_indicator: ^1.0.1 #web
  timeago: ^3.1.0 #web
  tutorial_coach_mark: ^1.2.2 #web
  url_launcher: ^6.0.20 #web
  uuid: ^3.0.5 #web
  validators: ^3.0.0 #web
  walletconnect_dart: ^0.0.10 #web
  walletconnect_secure_storage: ^1.0.0 #web
  web3dart: ^2.3.5 #web

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  source_gen: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/json/
    - assets/keys/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 100
