name: betticos
description: Social betting app. All rights reserved to WealthSecrets (www.wealthsecrets.io)

publish_to: "none"

version: 1.3.0+4

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.1.0+1
  another_flushbar: ^1.10.29
  auto_size_text: ^3.0.0
  barcode: ^2.2.3
  carousel_slider: ^4.0.0
  circular_reveal_animation: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  detectable_text_field: ^2.0.3
  dio: ^4.0.4
  faker: ^2.0.0
  file_picker: ^5.2.2
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  flutter_web3: ^2.1.9
  footer: ^0.0.4
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  google_sign_in: ^5.3.0
  http: ^0.13.4
  http_parser: ^4.0.2
  image: ^3.1.3
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  ionicons: ^0.1.2
  like_button: ^2.0.4
  logging: ^1.0.2
  lottie: ^1.3.0
  modal_bottom_sheet: ^2.1.2
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.5
  settings_ui: ^2.0.2
  share_plus: ^4.0.3
  shared_preferences: ^2.0.11
  slider_captcha: ^0.1.7
  step_progress_indicator: ^1.0.1
  timeago: ^3.1.0
  tutorial_coach_mark: ^1.2.2
  uuid: ^3.0.5
  validators: ^3.0.0
  webviewx: ^0.2.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  source_gen: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/json/
    - assets/keys/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 100
