class AssetImages {
  AssetImages._();
  static String logo = 'assets/images/logo.png';
  static String loginBg = 'assets/images/login_bg.png';
  static String profileImage = 'assets/images/profile_image.jpg';
  static String confusedFace = 'assets/images/confused-face.png';
  static String emptyBox = 'assets/images/empty-box.png';
  static String frustratedFace = 'assets/images/frustrated-face.png';
  static String arsenal = 'assets/images/arsenal.png';
  static String barcelona = 'assets/images/barcelona.png';
  static String chelsea = 'assets/images/chelsea.png';
  static String leicester = 'assets/images/leicester.png';
  static String manchester = 'assets/images/manchester.png';
  static String verified = 'assets/images/verified.jpeg';
  static String closeSmall = 'assets/images/close-small.png';
  static String caretDown = 'assets/images/caret-down.png';
  static String filter = 'assets/images/filter.png';
  static String facebook = 'assets/images/facebook.png';
  static String google = 'assets/images/google.png';
  static String walletConnect = 'assets/images/walletconnect.png';
  static String betting = 'assets/images/betting.png';
  static String transactionHisotry = 'assets/images/transaction_history.png';
  static String deposit = 'assets/images/deposit.png';
  static String withdrawal = 'assets/images/withdrawal.png';
  static String tansactionHistory = 'assets/images/trans-history.png';
  static String convert = 'assets/images/convert.png';
  static String bitcoinWallet = 'assets/images/bitcoin-wallet.png';
  static String wallet = 'assets/images/wallet.png';
  static String upDown = 'assets/images/up-down.png';
  static String copyFile = 'assets/images/copy.png';
}
